version: 2
updates:
- package-ecosystem: gomod
  directory: "/entrypoint"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/otiai10/copy
    versions:
    - 1.4.2
    - 1.5.1
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
